# Generated by Django 5.0.4 on 2025-12-11 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('created', 'Создана'), ('running', 'Запущена'), ('finished', 'Завершена')], default='created', max_length=20)),
            ],
            options={
                'ordering': ('-start_at',),
                'permissions': (('view_all_mailings', 'Can view all mailings (manager)'), ('can_disable_mailings', 'Can disable foreign mailings (manager)')),
            },
        ),
        migrations.CreateModel(
            name='MailingAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('success', 'Успешно'), ('failed', 'Не успешно')], max_length=20)),
                ('server_response', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('-attempted_at',),
                'permissions': (('view_all_attempts', 'Can view all mailing attempts (manager)'),),
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
            ],
            options={
                'ordering': ('-created_at',),
                'permissions': (('view_all_messages', 'Can view all messages (manager)'),),
            },
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('comment', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('full_name',),
                'permissions': (('view_all_recipients', 'Can view all recipients (manager)'),),
            },
        ),
    ]
