# Generated by Django 5.0.4 on 2025-12-11 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0004_rename_start_end_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'ordering': ('-start_time',), 'permissions': (('view_all_mailings', 'Can view all mailings (manager)'), ('can_disable_mailings', 'Can disable foreign mailings (manager)'))},
        ),
    ]
